version: '3.7'

services:
  web:
    build: .
    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 5678:5678
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
